package com.wxfw.util.Constant;

import com.wxfw.util.JsonUtils;
import com.wxfw.util.JwtUtils;

import java.util.Map;

/**
 * CurrentUserFactory
 *
 * @author gaohw
 * @date 2020/3/17
 */
public class CurrentUserFactory {

    public static String createToken(CurrentUser currentUser, String secret) {
        return JwtUtils.create(JsonUtils.toJsonString(currentUser), secret);
    }

    public static CurrentUser getCurrentUser(String token, String secret) {
        Map<String, Object> claims = JwtUtils.parse(token, secret);
        return new CurrentUser(claims);
    }

    public static void main(String[] args) {
        //eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiIwMDNmNzdhMzY2ZDY0YWE0ODlkM2Y0OGMzOWE3ODUyYiIsInBlcmlvZCI6NjA0ODAwLCJsb2dpblRpbWUiOjE2MDIwNDI3MjQwMzEsInBlcm1pc3Npb25zIjpbIm1lbWJlckxldmVsOmFkZCIsIm1hbGw6bGlzdCIsImNvdXBvbjphZGQiLCJob21lIiwiY29tbTplZGl0IiwiZ29vZHM6YWRkIiwidXNlcjphZGQiLCJnb29kczpsaXN0IiwiZ3JhZGVzOmFkZCIsImdyb3d0aENvbmZpZzphZGQiLCJwcm9maXRlOmVkaXQiLCJpbWFnZTphZGQiLCJtYWxsOmFkZCIsImNvbmZpZzphZGQiLCJzaWduOmVkaXQiLCJhcHBseTphZGQiLCJiYW5uZXI6YWRkIiwiaW1hZ2U6bGlzdCIsImNhdGVnb3JpZXM6YWRkIiwiZXhwcmVzczphZGQiLCJjYXRlZ29yaWVzOmVkaXQiLCJtZW1iZXJMZXZlbDpsaXN0Iiwicm9sZXM6YWRkIiwiYmFubmVyOmVkaXQiLCJtYWxsOmVkaXQiLCJtZW51OmFkZCIsInVzZXI6ZWRpdCIsImdyYWRlczpsaXN0IiwibWVtYmVyTGV2ZWw6ZGVsIiwiY291cG9uOmVkaXQiLCJjYXRlZ29yaWVzOmxpc3QiLCJpbWFnZTplZGl0IiwiZ3JhZGVzOmVkaXQiLCJhcHBseTplZGl0IiwiYmFubmVyOmxpc3QiLCJ1c2VyOmxpc3QiLCJleHByZXNzOmVkaXQiLCJncm93dGhDb25maWc6ZWRpdCIsImdvb2RzOmVkaXQiLCJjb25maWc6ZWRpdCIsInByb2R1Y3QiLCJhcHBseTpkZWwiLCJtYWxsOmRlbCIsIm1lbWJlckxldmVsOmVkaXQiLCJtZW51OmVkaXQiLCJleHByZXNzOmRlbCIsImFwcGx5Omxpc3QiLCJncm93dGhDb25maWc6ZGVsIiwiZ29vZHM6ZGVsIiwiZ3JhZGVzOmRlbCIsInJvbGVzOmVkaXQiLCJjYXRlZ29yaWVzOmRlbCIsInJvbGVzOmxpc3QiLCJjb25maWc6ZGVsIiwiY291cG9uOmRlbCIsImJhbm5lcjpkZWwiLCJncm93dGhDb25maWc6bGlzdCIsImNvdXBvbjpsaXN0Iiwib3JkZXIiLG51bGwsImltYWdlOmRlbCIsInVzZXI6ZGVsIiwicHJvZml0ZTpsaXN0IiwibWVtYmVyIiwibWVudTpkZWwiLG51bGwsImdvb2RzOmFwcHJvdmUiLG51bGwsIm1lbnU6bGlzdCIsbnVsbCwibG9nczpsaXN0IiwiY291cG9uOmFwcHJvdmVsIixudWxsLCJzaG9wIixudWxsLG51bGwsInN0YXRpc3RpY3MiLCJtZXNzYWdlOmxpc3QiLCJyb2xlczpkZWwiLG51bGwsImNvbW06bGlzdCIsIndlYiIsImRpc3RyaWJ1dGlvbiIsbnVsbCwiZXhwcmVzczpsaXN0IixudWxsLG51bGwsInN5c3RlbSIsIiIsIm1hcmtldGluZyIsIm9wZW46bGlzdCIsbnVsbCwic2lnbjppbmZvIiwid3hTaG9wIiwic3Rld2FyZDpsaXN0IiwiYXVkaXQ6YWRkIiwiYWRtaW5BcHAiLCJjb25maWc6bGlzdCIsbnVsbCwic21hbGxTaG9wIiwic2hvcEFwcCJdLCJyb2xlcyI6WyLotoXnuqfnrqHnkIblkZgiXSwidHlwZSI6Ik9QRVJBVE9SIiwiYWNjb3VudCI6ImFkbWluIn0.fsB_9kiv6dfHiFvn8nHawY8aoss8Qtp8bJSfyb0isxrTgfJmtknrDEelRBJlwa0szK5JvqO8dV13XNhtwSnR_g
        CurrentUser currentUser = getCurrentUser("eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiIwMDNmNzdhMzY2ZDY0YWE0ODlkM2Y0OGMzOWE3ODUyYiIsInBlcmlvZCI6NjA0ODAwLCJsb2dpblRpbWUiOjE2MDIwNDI3MjQwMzEsInBlcm1pc3Npb25zIjpbIm1lbWJlckxldmVsOmFkZCIsIm1hbGw6bGlzdCIsImNvdXBvbjphZGQiLCJob21lIiwiY29tbTplZGl0IiwiZ29vZHM6YWRkIiwidXNlcjphZGQiLCJnb29kczpsaXN0IiwiZ3JhZGVzOmFkZCIsImdyb3d0aENvbmZpZzphZGQiLCJwcm9maXRlOmVkaXQiLCJpbWFnZTphZGQiLCJtYWxsOmFkZCIsImNvbmZpZzphZGQiLCJzaWduOmVkaXQiLCJhcHBseTphZGQiLCJiYW5uZXI6YWRkIiwiaW1hZ2U6bGlzdCIsImNhdGVnb3JpZXM6YWRkIiwiZXhwcmVzczphZGQiLCJjYXRlZ29yaWVzOmVkaXQiLCJtZW1iZXJMZXZlbDpsaXN0Iiwicm9sZXM6YWRkIiwiYmFubmVyOmVkaXQiLCJtYWxsOmVkaXQiLCJtZW51OmFkZCIsInVzZXI6ZWRpdCIsImdyYWRlczpsaXN0IiwibWVtYmVyTGV2ZWw6ZGVsIiwiY291cG9uOmVkaXQiLCJjYXRlZ29yaWVzOmxpc3QiLCJpbWFnZTplZGl0IiwiZ3JhZGVzOmVkaXQiLCJhcHBseTplZGl0IiwiYmFubmVyOmxpc3QiLCJ1c2VyOmxpc3QiLCJleHByZXNzOmVkaXQiLCJncm93dGhDb25maWc6ZWRpdCIsImdvb2RzOmVkaXQiLCJjb25maWc6ZWRpdCIsInByb2R1Y3QiLCJhcHBseTpkZWwiLCJtYWxsOmRlbCIsIm1lbWJlckxldmVsOmVkaXQiLCJtZW51OmVkaXQiLCJleHByZXNzOmRlbCIsImFwcGx5Omxpc3QiLCJncm93dGhDb25maWc6ZGVsIiwiZ29vZHM6ZGVsIiwiZ3JhZGVzOmRlbCIsInJvbGVzOmVkaXQiLCJjYXRlZ29yaWVzOmRlbCIsInJvbGVzOmxpc3QiLCJjb25maWc6ZGVsIiwiY291cG9uOmRlbCIsImJhbm5lcjpkZWwiLCJncm93dGhDb25maWc6bGlzdCIsImNvdXBvbjpsaXN0Iiwib3JkZXIiLG51bGwsImltYWdlOmRlbCIsInVzZXI6ZGVsIiwicHJvZml0ZTpsaXN0IiwibWVtYmVyIiwibWVudTpkZWwiLG51bGwsImdvb2RzOmFwcHJvdmUiLG51bGwsIm1lbnU6bGlzdCIsbnVsbCwibG9nczpsaXN0IiwiY291cG9uOmFwcHJvdmVsIixudWxsLCJzaG9wIixudWxsLG51bGwsInN0YXRpc3RpY3MiLCJtZXNzYWdlOmxpc3QiLCJyb2xlczpkZWwiLG51bGwsImNvbW06bGlzdCIsIndlYiIsImRpc3RyaWJ1dGlvbiIsbnVsbCwiZXhwcmVzczpsaXN0IixudWxsLG51bGwsInN5c3RlbSIsIiIsIm1hcmtldGluZyIsIm9wZW46bGlzdCIsbnVsbCwic2lnbjppbmZvIiwid3hTaG9wIiwic3Rld2FyZDpsaXN0IiwiYXVkaXQ6YWRkIiwiYWRtaW5BcHAiLCJjb25maWc6bGlzdCIsbnVsbCwic21hbGxTaG9wIiwic2hvcEFwcCJdLCJyb2xlcyI6WyLotoXnuqfnrqHnkIblkZgiXSwidHlwZSI6Ik9QRVJBVE9SIiwiYWNjb3VudCI6ImFkbWluIn0.fsB_9kiv6dfHiFvn8nHawY8aoss8Qtp8bJSfyb0isxrTgfJmtknrDEelRBJlwa0szK5JvqO8dV13XNhtwSnR_g", Constants.TOKEN.JWT_SECURITY_KEY);
        System.out.println(currentUser.isLoggedIn());
    }


}
